name: 🌅 Morning Market Scanner

on:
  schedule:
    - cron: "30 12 * * 1-5"  # 8:30 AM EST (adjust if repo uses UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Google credentials file
        run: echo '${{ secrets.GOOGLE_CREDS_JSON }}' > google_creds.json

      - name: Run morning scan
        env:
          ALPACA_KEY: ${{ secrets.ALPACA_KEY }}
          ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOOGLE_CREDS_FILE: "google_creds.json"
        run: python LastDaytradingbot.py morning
